In [80]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
t1 = tf.constant(3)  # constant
t1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [81]:
t1 = tf.constant([1,2,3])
t1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [82]:
t2 = tf.constant([[1,2,3],[4,5,6]])
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [88]:
t2.numpy() # numpy elements

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
t2.shape # shape

TensorShape([2, 3])

In [87]:
tf.rank(t2)  # dimension

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [89]:
# Variable

In [90]:
tv1 = tf.Variable(3,dtype=tf.float32,name='var1')  # variable tensor
tv1

<tf.Variable 'var1:0' shape=() dtype=float32, numpy=3.0>

In [9]:
tv2 = tf.Variable([10,12,13,6,9,5],name='var1')  # variable tensor
tv2

<tf.Variable 'var1:0' shape=(6,) dtype=int32, numpy=array([10, 12, 13,  6,  9,  5])>

In [91]:
tv3 = tf.Variable([[10,12,13],[6,9,5]],name='var1')  # 2D - variable tensor
tv3

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 12, 13],
       [ 6,  9,  5]])>

## Indexing , Slicing and Changing

In [92]:
tv2

<tf.Variable 'var1:0' shape=(6,) dtype=int32, numpy=array([10, 12, 13,  6,  9,  5])>

In [93]:
tv2[0]  # indexing

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [11]:
tv2[0:3] # slicing

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 12, 13])>

In [94]:
tv3

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 12, 13],
       [ 6,  9,  5]])>

In [95]:
tv3[0,1].assign(100)
tv3

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[ 10, 100,  13],
       [  6,   9,   5]])>

#### Creating Different Tensor Variables

In [12]:
tv3 = tf.random.normal([4,3]) # creating normal dist
tv3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.72933125, -0.12714861, -0.04499909],
       [-1.5421929 , -0.15424512, -0.0499175 ],
       [-0.0752845 ,  0.43112552,  0.82058555],
       [ 1.6732407 ,  2.5628695 , -1.3349689 ]], dtype=float32)>

In [96]:
tv3 = tf.random.uniform([4,3]) # creating normal dist
tv3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.42153823, 0.3078686 , 0.01021552],
       [0.7163876 , 0.33328676, 0.9246019 ],
       [0.44385517, 0.44001722, 0.93251634],
       [0.24456811, 0.00701845, 0.6696799 ]], dtype=float32)>

In [16]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [13]:
tv4 = tf.Variable(tv3)
tv4

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.72933125, -0.12714861, -0.04499909],
       [-1.5421929 , -0.15424512, -0.0499175 ],
       [-0.0752845 ,  0.43112552,  0.82058555],
       [ 1.6732407 ,  2.5628695 , -1.3349689 ]], dtype=float32)>

In [28]:
tf1 = tf.reshape(tf1,(1,4))
tf1

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>

## Arithmetic Operations

In [29]:
tf1 = tf.Variable([[1,2],[3,4]])
tf2= tf.Variable([[10,20],[30,40]])

In [30]:
tf1+tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 22],
       [33, 44]])>

In [31]:
tf1-tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -9, -18],
       [-27, -36]])>

In [32]:
tf1*tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  40],
       [ 90, 160]])>

In [34]:
tf.pow(tf1,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [35]:
tf1 = tf.Variable([1.,2,3])
tf.sqrt(tf1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

In [36]:
a =  tf.Variable([2.,3,4])
b = tf.Variable([3.,2.1,2])
tf.tensordot(a,b,1)

<tf.Tensor: shape=(), dtype=float32, numpy=20.3>

In [98]:
a =  tf.Variable([2.,3,4])
b = tf.Variable([3.,2,5])
tf.tensordot(a,b,0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 6.,  4., 10.],
       [ 9.,  6., 15.],
       [12.,  8., 20.]], dtype=float32)>

## Linear Algebra 

In [38]:
a =  tf.Variable([[2.,3],[1,4]])
b = tf.Variable([[3.,2.1],[3,2]])
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15. , 10.2],
       [15. , 10.1]], dtype=float32)>

In [39]:
tf.linalg.eigvals(a)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.99999994+0.j, 5.0000005 +0.j], dtype=complex64)>

In [40]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [41]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 1.],
       [3., 4.]], dtype=float32)>

## Optimizing the Coefficients for miminum loss in Tensorflow

In [141]:
inp=tf.constant([[1,23,0.5,1],[1,26,2,1],[1,34,6,2],[1,34,10,1],[1,22,0,1],
                 [1,27,1,2],[1,36,11,1],[1,35,7,2]])
inp.numpy()

array([[ 1. , 23. ,  0.5,  1. ],
       [ 1. , 26. ,  2. ,  1. ],
       [ 1. , 34. ,  6. ,  2. ],
       [ 1. , 34. , 10. ,  1. ],
       [ 1. , 22. ,  0. ,  1. ],
       [ 1. , 27. ,  1. ,  2. ],
       [ 1. , 36. , 11. ,  1. ],
       [ 1. , 35. ,  7. ,  2. ]], dtype=float32)

In [142]:
out=tf.constant([[2],[3],[6],[10],[1.8],[2.5],[10.2],[7.5]]) # output/ target - regression
out.numpy()

array([[ 2. ],
       [ 3. ],
       [ 6. ],
       [10. ],
       [ 1.8],
       [ 2.5],
       [10.2],
       [ 7.5]], dtype=float32)

In [143]:
def inp_weig_mul(inp,wei):
    return tf.tensordot(inp,wei,1) # output

In [144]:
wei = tf.Variable([1.,1.,1.,1.])
loss =lambda:tf.reduce_sum((inp_weig_mul(inp,wei)-tf.transpose(out))**2)

In [145]:
opti=tf.optimizers.Adam(learning_rate=0.01) # Use adam optmizer (Gradient descent variant to find coeff)

In [146]:
for i in range(100):
    opti.minimize(loss,var_list=[wei])

In [147]:
wei.numpy()

array([0.27072236, 0.27484572, 0.2920162 , 0.2689417 ], dtype=float32)